"""
Temporal activity wrapper and workflow proxy for knowledge service query repository.

This module contains:
1. The @temporal_activity_registration decorated class that wraps the pure backend
   MinioKnowledgeServiceQueryRepository as Temporal activities (for worker use only)
2. The @temporal_workflow_proxy decorated class that automatically generates
   workflow methods that delegate to activities

The activity names follow the pattern: julee.knowledge_service_query_repo.minio.{method}
"""

from util.repos.temporal.decorators import temporal_activity_registration, temporal_workflow_proxy
from julee_example.repositories.minio.knowledge_service_query import MinioKnowledgeServiceQueryRepository
from julee_example.repositories.knowledge_service_query import KnowledgeServiceQueryRepository

# Activity name base used by both the temporal repository and workflow proxy
ACTIVITY_NAME_BASE = "julee.knowledge_service_query_repo.minio"


@temporal_activity_registration(ACTIVITY_NAME_BASE)
class TemporalMinioKnowledgeServiceQueryRepository(MinioKnowledgeServiceQueryRepository):
    """Temporal activity wrapper for MinioKnowledgeServiceQueryRepository."""

    pass


@temporal_workflow_proxy(
    activity_base=ACTIVITY_NAME_BASE,
    default_timeout_seconds=30,
    retry_methods=["save", "generate_id"]
)
class WorkflowKnowledgeServiceQueryRepositoryProxy(KnowledgeServiceQueryRepository):
    """
    Workflow implementation of KnowledgeServiceQueryRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy decorator.
    """

    pass
