"""
Temporal activity wrapper and workflow proxy for inventory repository.

This module contains:
1. The @temporal_activity_registration decorated class that wraps the pure
   backend MinioInventoryRepository as Temporal activities (for worker use)
2. The @temporal_workflow_proxy decorated class that automatically generates
   workflow methods that delegate to activities

The activity names follow the pattern: sample.inventory_repo.minio.{method}
"""

from util.repos.temporal.decorators import (
    temporal_activity_registration,
    temporal_workflow_proxy,
)
from sample.repos.minio.inventory import MinioInventoryRepository
from sample.repositories import InventoryRepository

# Activity name base used by both the temporal repository and workflow proxy
ACTIVITY_NAME_BASE = "sample.inventory_repo.minio"


@temporal_activity_registration(ACTIVITY_NAME_BASE)
class TemporalMinioInventoryRepository(MinioInventoryRepository):
    """Temporal activity wrapper for MinioInventoryRepository."""

    pass


@temporal_workflow_proxy(
    activity_base=ACTIVITY_NAME_BASE,
    default_timeout_seconds=10,
    retry_methods=["reserve_items"],
)
class WorkflowInventoryRepositoryProxy(InventoryRepository):
    """
    Workflow implementation of InventoryRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass
