"""
Temporal activity wrapper and workflow proxy for order repository.

This module contains:
1. The @temporal_activity_registration decorated class that wraps the pure
   backend MinioOrderRepository as Temporal activities (for worker use)
2. The @temporal_workflow_proxy decorated class that automatically generates
   workflow methods that delegate to activities

The activity names follow the pattern: sample.order_repo.minio.{method}
"""

from util.repos.temporal.decorators import (
    temporal_activity_registration,
    temporal_workflow_proxy,
)
from sample.repos.minio.order import MinioOrderRepository
from sample.repositories import OrderRepository

# Activity name base used by both the temporal repository and workflow proxy
ACTIVITY_NAME_BASE = "sample.order_repo.minio"


@temporal_activity_registration(ACTIVITY_NAME_BASE)
class TemporalMinioOrderRepository(MinioOrderRepository):
    """Temporal activity wrapper for MinioOrderRepository."""

    pass


@temporal_workflow_proxy(
    activity_base=ACTIVITY_NAME_BASE,
    default_timeout_seconds=10,
)
class WorkflowOrderRepositoryProxy(OrderRepository):
    """
    Workflow implementation of OrderRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass
