"""
Workflow-safe proxy classes for the sample domain.

This module contains all @temporal_workflow_proxy decorated classes that
delegate to Temporal activities from within workflows. These classes are
isolated from backend imports to avoid Temporal's workflow sandbox
restrictions.

The proxy classes automatically generate methods that call
workflow.execute_activity() with the appropriate activity names, timeouts,
and retry policies.
"""

from util.temporal.decorators import temporal_workflow_proxy
from sample.repositories import (
    OrderRepository,
    PaymentRepository,
    InventoryRepository,
    OrderRequestRepository,
)

# Import activity name bases from shared module
from sample.repos.temporal.activity_names import (
    ORDER_ACTIVITY_BASE,
    PAYMENT_ACTIVITY_BASE,
    INVENTORY_ACTIVITY_BASE,
    ORDER_REQUEST_ACTIVITY_BASE,
)


@temporal_workflow_proxy(
    activity_base=ORDER_ACTIVITY_BASE,
    default_timeout_seconds=10,
)
class WorkflowOrderRepositoryProxy(OrderRepository):
    """
    Workflow implementation of OrderRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass


@temporal_workflow_proxy(
    activity_base=PAYMENT_ACTIVITY_BASE,
    default_timeout_seconds=10,
    retry_methods=["process_payment", "refund_payment"],
)
class WorkflowPaymentRepositoryProxy(PaymentRepository):
    """
    Workflow implementation of PaymentRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass


@temporal_workflow_proxy(
    activity_base=INVENTORY_ACTIVITY_BASE,
    default_timeout_seconds=10,
    retry_methods=["reserve_items"],
)
class WorkflowInventoryRepositoryProxy(InventoryRepository):
    """
    Workflow implementation of InventoryRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass


@temporal_workflow_proxy(
    activity_base=ORDER_REQUEST_ACTIVITY_BASE,
    default_timeout_seconds=10,
)
class WorkflowOrderRequestRepositoryProxy(OrderRequestRepository):
    """
    Workflow implementation of OrderRequestRepository that calls activities.
    All methods are automatically generated by the @temporal_workflow_proxy
    decorator.
    """

    pass


# Export the workflow proxy classes
__all__ = [
    "WorkflowOrderRepositoryProxy",
    "WorkflowPaymentRepositoryProxy",
    "WorkflowInventoryRepositoryProxy",
    "WorkflowOrderRequestRepositoryProxy",
]
