FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application code (all domains) to /app
COPY . /app

# Add the app directory to PYTHONPATH to allow module resolution
ENV PYTHONPATH "/app"

CMD ["uvicorn", "sample.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
