services:
  docs:
    build:
      context: ..
      dockerfile: docs/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app:/app/sample:/app/julee_example:/app/util
    restart: unless-stopped
    stdin_open: true
    tty: true