name: Type Check

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run type checking
      run: make quality-types
      
    - name: Upload type check reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: type-check-reports-${{ github.run_id }}
        path: reports/mypy.txt
        retention-days: 30
        
    - name: Check for type errors
      if: always()
      run: |
        if grep -q "error:" reports/mypy.txt; then
          echo "Type checking failed!"
          cat reports/mypy.txt
          exit 1
        fi
